"""Fix Volunteer-Activity Relationship

Revision ID: 5a897799d6b4
Revises: 42fc5416001c
Create Date: 2025-03-28 00:44:21.018222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a897799d6b4'
down_revision = '42fc5416001c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_activity',
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('volunteer_id', 'activity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_activity')
    # ### end Alembic commands ###
